version: '3'
services:
  negotiation-app:
    container_name: negotiation-app
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - npm_config_unsafe_perm=true
    ports:
      - 8080:8080
    command:
      - /bin/sh
      - '-c'
      - 'npm run dev'
